version: '3.9'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:legacy    
    container_name: mat-keycloak
    hostname: mat-keycloak
    ports: 
      - "8081:8080"
    volumes:
      - ./config:/opt/jboss/keycloak/imports
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_SCHEMA: public
      DB_PASSWORD: changeit
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: changeit 
      KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/mat-realm.json -Dkeycloak.profile.feature.upload_scripts=enabled                
      depends_on: postgres
      
  postgres:
    image: postgres:14-alpine
    ports: 
      - "8001:5432"
    restart: always
    container_name: postgres_keycloak
    user: postgres
    environment:
      - "POSTGRES_DB=keycloak"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=changeit"     
    volumes:
      - postgres_data_keycloak:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_keycloak:
      driver: local
  
